version: '3'

services:
  web:
    container_name: web
    ports:
      - "8090:8090"
    build:
      context: .
      dockerfile: deploy/web.dockerfile
    depends_on:
      - api
    tty: true
    volumes:
      - ./web:/app

  api:
    container_name: api
    ports:
      - "8081:8081"
    build:
      context: .
      dockerfile: deploy/api.dockerfile
      args:
        - SQL_DB=$SQL_DB
        - SQL_USER=$SQL_USER
        - SQL_PASSWORD=$SQL_PASSWORD
        - SQL_PORT=$SQL_PORT
    depends_on:
      - db
    tty: true
    volumes:
      - ./api:/go/app

  db:
    container_name: db
    build:
      context: .
      dockerfile: deploy/db.dockerfile
      args:
        - SQL_DB=$SQL_DB
        - SQL_USER=$SQL_USER
        - SQL_PASSWORD=$SQL_PASSWORD
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  proxy:
    container_name: proxy
    build:
      context: .
      dockerfile: deploy/proxy.dockerfile
    ports:
      - $PROXY_PORT:$PROXY_PORT
    depends_on:
      - web
      - api
    volumes:
      - ./proxy:/app